import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'kz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.signIn': 'Sign In',
    'nav.skipToMain': 'Skip to main content',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.homeLabel': 'RSL Kazakhstan Home',
    
    // Brand
    'brand.name': 'RSL Kazakhstan',
    'brand.tagline': 'Learn with Heart',
    'brand.mission': 'Empowering the deaf and hard-of-hearing community in Kazakhstan through accessible, high-quality Russian sign language education.',
    
    // Common
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.contact': 'Contact',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.location': 'Location',
    'common.copyright': '© 2024 RSL Kazakhstan. All rights reserved. Made with ❤️ for the deaf community.',
    'common.followUs': 'Follow us:',
    'common.quickLinks': 'Quick Links',
    'common.support': 'Support',
    
    // Home page
    'home.heroTitle': 'Learn Russian Sign Language in Kazakhstan',
    'home.heroSubtitle': 'Join RSL Kazakhstan and connect with the deaf and hard-of-hearing community. Start your journey in Russian Sign Language today.',
    'home.startLearning': 'Start Learning Today',
    'home.exploreCourses': 'Explore Our Courses',
    'home.watchIntro': 'Watch Introduction',
    'home.whyChoose': 'Why Choose RSL Kazakhstan?',
    'home.qualityInstruction': 'Quality Instruction',
    'home.qualityDesc': 'Learn from certified RSL instructors with high-quality video content and clear demonstrations.',
    'home.flexibleLearning': 'Flexible Learning',
    'home.flexibleDesc': 'Study at your own pace with 24/7 access to courses on any device.',
    'home.supportiveCommunity': 'Supportive Community',
    'home.supportiveDesc': 'Join a welcoming community of learners and native signers.',
    'home.accessibleDesign': 'Accessible Design',
    'home.accessibleDesc': 'Built with accessibility in mind, ensuring everyone can learn effectively.',
    'home.testimonialTitle': 'What Our Students Say',
    'home.testimonial1': 'RSL Kazakhstan changed my life. The instructors are patient and the community is so welcoming. I can finally communicate with my deaf daughter.',
    'home.testimonial1Author': 'Aida K.',
    'home.testimonial1Role': 'Parent',
    'home.testimonial2': 'The video quality is excellent and the structured approach helped me progress quickly. Highly recommend!',
    'home.testimonial2Author': 'Marat S.',
    'home.testimonial2Role': 'Professional',
    'home.testimonial3': 'As a deaf student, I appreciate how accessible and inclusive this platform is. Thank you RSL Kazakhstan!',
    'home.testimonial3Author': 'Zhanna B.',
    'home.testimonial3Role': 'Student',
    'home.joinCommunity': 'Join hundreds of students learning sign language with RSL Kazakhstan.',
    'home.readyToStart': 'Ready to start your RSL journey?',
    
    // Courses page
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Comprehensive Russian Sign Language courses for all skill levels',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate', 
    'courses.advanced': 'Advanced',
    'courses.allLevels': 'All Levels',
    'courses.lessons': 'lessons',
    'courses.minutes': 'minutes',
    'courses.enrollNow': 'Enroll Now',
    'courses.viewDetails': 'View Details',
    'courses.alphabetTitle': 'RSL Alphabet & Numbers',
    'courses.alphabetDesc': 'Master the fundamentals of Russian Sign Language with the alphabet and number system.',
    'courses.basicTitle': 'Basic Conversations',
    'courses.basicDesc': 'Learn essential phrases and vocabulary for everyday conversations.',
    'courses.familyTitle': 'Family & Relationships',
    'courses.familyDesc': 'Express family relationships, emotions, and personal connections.',
    'courses.workTitle': 'Professional & Business RSL',
    'courses.workDesc': 'Advance your career with professional sign language skills.',
    
    // About page
    'about.title': 'About RSL Kazakhstan',
    'about.subtitle': 'Founded in 2021, RSL Kazakhstan is the first comprehensive sign language education platform dedicated to serving the deaf and hard-of-hearing community in Kazakhstan and Central Asia.',
    'about.ourMission': 'Our Mission',
    'about.ourMissionDesc': 'To make Russian Sign Language accessible to everyone in Kazakhstan through innovative online education, fostering communication and inclusion within the deaf community.',
    'about.ourTeam': 'Meet Our Team',
    'about.instructor1Name': 'Elena Volkov',
    'about.instructor1Role': 'Lead RSL Instructor & Founder',
    'about.instructor1Bio': 'Certified RSL interpreter with 15+ years experience. Passionate about making sign language accessible to all.',
    'about.instructor1Cred1': 'Certified RSL Interpreter',
    'about.instructor1Cred2': 'M.Ed. Special Education',
    'about.instructor2Name': 'Dmitri Nazarbayev',
    'about.instructor2Role': 'Senior RSL Instructor',
    'about.instructor2Bio': 'Deaf community advocate and experienced educator specializing in beginner-friendly RSL instruction.',
    'about.instructor2Cred1': 'Native RSL Speaker',
    'about.instructor2Cred2': 'Community Advocate',
    'about.coreValues': 'Our Core Values',
    'about.accessibilityTitle': 'Accessibility First',
    'about.accessibilityDesc': 'Every feature is designed with accessibility in mind, ensuring equal access for all learners.',
    'about.communityTitle': 'Community Focus',
    'about.communityDesc': 'Building bridges between hearing and deaf communities through education and understanding.',
    'about.qualityTitle': 'Quality Education',
    'about.qualityDesc': 'High-standard curriculum developed by certified instructors and community experts.',
    'about.cultureTitle': 'Cultural Respect',
    'about.cultureDesc': 'Honoring deaf culture while adapting RSL education for the Kazakhstani context.',
    'about.principlesNote': 'These core principles guide everything we do at RSL Kazakhstan.',
    'about.ourStory': 'Our Story',
    'about.storyText1': 'RSL Kazakhstan was born from a simple yet powerful realization: the deaf and hard-of-hearing community in Kazakhstan deserved access to high-quality sign language education in their own region.',
    'about.storyText2': 'Our founder, Elena Volkov, noticed the lack of comprehensive RSL resources available locally. Most materials were either outdated, inaccessible, or not culturally relevant to the Central Asian context.',
    'about.storyText3': 'In 2021, we launched RSL Kazakhstan as an online platform that could reach students across the country, breaking down geographical barriers and providing consistent, professional instruction.',
    'about.storyText4': 'Today, we\'re proud to serve hundreds of students, from parents learning to communicate with their deaf children to professionals seeking to serve the deaf community better.',
    
    // Contact page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team. We\'re here to help you on your RSL learning journey.',
    'contact.getInTouch': 'Get in Touch',
    'contact.name': 'Full Name',
    'contact.namePlaceholder': 'Enter your full name',
    'contact.email': 'Email Address',
    'contact.emailPlaceholder': 'Enter your email address',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'What is this regarding?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help you...',
    'contact.sendMessage': 'Send Message',
    'contact.contactInfo': 'Contact Information',
    'contact.emailLabel': 'Email',
    'contact.emailValue': 'info@rslkazakhstan.kz',
    'contact.phoneLabel': 'Phone',
    'contact.phoneValue': '+7 (727) 123-4567',
    'contact.addressLabel': 'Address',
    'contact.addressValue': 'Almaty, Kazakhstan',
    'contact.hoursLabel': 'Support Hours',
    'contact.hoursValue': 'Monday - Friday, 9 AM - 6 PM (GMT+6)',
    'contact.socialMedia': 'Social Media',
    'contact.followText': 'Follow us on social media for updates, tips, and community highlights.',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faqSubtitle': 'Find quick answers to common questions about RSL Kazakhstan and our courses.',
    'contact.faq1Q': 'How do I start learning RSL?',
    'contact.faq1A': 'Simply sign up for a free account and browse our beginner courses. We recommend starting with the RSL Alphabet & Numbers course.',
    'contact.faq2Q': 'Are the courses suitable for complete beginners?',
    'contact.faq2A': 'Absolutely! Our courses are designed with beginners in mind, featuring clear instructions and step-by-step progression.',
    'contact.faq3Q': 'Can I learn at my own pace?',
    'contact.faq3A': 'Yes! All our courses are self-paced. You can learn whenever it\'s convenient for you, 24/7.',
    'contact.faq4Q': 'What type of sign language do you teach?',
    'contact.faq4A': 'Currently, we focus on Russian Sign Language (RSL), but we incorporate cultural context relevant to Kazakhstan and Central Asia.',
    'contact.faq5Q': 'Do you offer certificates?',
    'contact.faq5A': 'Yes, we provide certificates of completion for each course you finish successfully.',
    
    // Footer
    'footer.helpCenter': 'Help Center',
    'footer.accessibility': 'Accessibility',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.courses': 'Курсы',
    'nav.about': 'О нас',
    'nav.contact': 'Контакты',
    'nav.signIn': 'Войти',
    'nav.skipToMain': 'Перейти к основному содержанию',
    'nav.openMenu': 'Открыть меню',
    'nav.closeMenu': 'Закрыть меню',
    'nav.homeLabel': 'РЖЯ Казахстан Главная',
    
    // Brand
    'brand.name': 'РЖЯ Казахстан',
    'brand.tagline': 'Учись с душой',
    'brand.mission': 'Расширение возможностей глухих и слабослышащих в Казахстане через доступное, высококачественное образование русского жестового языка.',
    
    // Common
    'common.learnMore': 'Узнать больше',
    'common.getStarted': 'Начать',
    'common.contact': 'Контакты',
    'common.email': 'Эл. почта',
    'common.phone': 'Телефон',
    'common.location': 'Местоположение',
    'common.copyright': '© 2024 РЖЯ Казахстан. Все права защищены. Создано с ❤️ для сообщества глухих.',
    'common.followUs': 'Подписывайтесь:',
    'common.quickLinks': 'Быстрые ссылки',
    'common.support': 'Поддержка',
    
    // Home page
    'home.heroTitle': 'Изучайте русский жестовый язык в Казахстане',
    'home.heroSubtitle': 'Присоединяйтесь к РЖЯ Казахстан и общайтесь с сообществом глухих и слабослышащих. Начните свое путешествие в мир русского жестового языка сегодня.',
    'home.startLearning': 'Начать обучение сегодня',
    'home.exploreCourses': 'Изучить наши курсы',
    'home.watchIntro': 'Смотреть введение',
    'home.whyChoose': 'Почему выбирают РЖЯ Казахстан?',
    'home.qualityInstruction': 'Качественное обучение',
    'home.qualityDesc': 'Учитесь у сертифицированных инструкторов РЖЯ с высококачественным видеоконтентом и четкими демонстрациями.',
    'home.flexibleLearning': 'Гибкое обучение',
    'home.flexibleDesc': 'Учитесь в своем темпе с круглосуточным доступом к курсам на любом устройстве.',
    'home.supportiveCommunity': 'Поддерживающее сообщество',
    'home.supportiveDesc': 'Присоединяйтесь к гостеприимному сообществу учащихся и носителей жестового языка.',
    'home.accessibleDesign': 'Доступный дизайн',
    'home.accessibleDesc': 'Создано с учетом доступности, обеспечивая эффективное обучение для всех.',
    'home.testimonialTitle': 'Что говорят наши студенты',
    'home.testimonial1': 'РЖЯ Казахстан изменил мою жизнь. Инструкторы терпеливы, а сообщество очень дружелюбное. Теперь я могу общаться со своей глухой дочерью.',
    'home.testimonial1Author': 'Аида К.',
    'home.testimonial1Role': 'Родитель',
    'home.testimonial2': 'Отличное качество видео и структурированный подход помогли мне быстро прогрессировать. Очень рекомендую!',
    'home.testimonial2Author': 'Марат С.',
    'home.testimonial2Role': 'Профессионал',
    'home.testimonial3': 'Как глухой студент, я ценю, насколько доступна и инклюзивна эта платформа. Спасибо РЖЯ Казахстан!',
    'home.testimonial3Author': 'Жанна Б.',
    'home.testimonial3Role': 'Студент',
    'home.joinCommunity': 'Присоединяйтесь к сотням студентов, изучающих жестовый язык с РЖЯ Казахстан.',
    'home.readyToStart': 'Готовы начать свое путешествие в мир РЖЯ?',
    
    // Courses page
    'courses.title': 'Наши курсы',
    'courses.subtitle': 'Комплексные курсы русского жестового языка для всех уровней',
    'courses.beginner': 'Начинающий',
    'courses.intermediate': 'Средний',
    'courses.advanced': 'Продвинутый',
    'courses.allLevels': 'Все уровни',
    'courses.lessons': 'уроков',
    'courses.minutes': 'минут',
    'courses.enrollNow': 'Записаться сейчас',
    'courses.viewDetails': 'Подробнее',
    'courses.alphabetTitle': 'Алфавит и числа РЖЯ',
    'courses.alphabetDesc': 'Освойте основы русского жестового языка с алфавитом и системой счисления.',
    'courses.basicTitle': 'Базовые разговоры',
    'courses.basicDesc': 'Изучите основные фразы и словарь для повседневного общения.',
    'courses.familyTitle': 'Семья и отношения',
    'courses.familyDesc': 'Выражайте семейные отношения, эмоции и личные связи.',
    'courses.workTitle': 'Профессиональный и деловой РЖЯ',
    'courses.workDesc': 'Продвиньте свою карьеру с профессиональными навыками жестового языка.',
    
    // About page
    'about.title': 'О РЖЯ Казахстан',
    'about.subtitle': 'Основанная в 2021 году, РЖЯ Казахстан - это первая комплексная платформа обучения жестовому языку, посвященная служению сообществу глухих и слабослышащих в Казахстане и Центральной Азии.',
    'about.ourMission': 'Наша миссия',
    'about.ourMissionDesc': 'Сделать русский жестовый язык доступным для всех в Казахстане через инновационное онлайн-образование, способствуя общению и включению в сообщество глухих.',
    'about.ourTeam': 'Познакомьтесь с нашей командой',
    'about.instructor1Name': 'Елена Волкова',
    'about.instructor1Role': 'Ведущий инструктор РЖЯ и основатель',
    'about.instructor1Bio': 'Сертифицированный переводчик РЖЯ с более чем 15-летним опытом. Увлечена тем, чтобы сделать жестовый язык доступным для всех.',
    'about.instructor1Cred1': 'Сертифицированный переводчик РЖЯ',
    'about.instructor1Cred2': 'Магистр специального образования',
    'about.instructor2Name': 'Дмитрий Назарбаев',
    'about.instructor2Role': 'Старший инструктор РЖЯ',
    'about.instructor2Bio': 'Защитник сообщества глухих и опытный педагог, специализирующийся на обучении РЖЯ для начинающих.',
    'about.instructor2Cred1': 'Носитель РЖЯ',
    'about.instructor2Cred2': 'Общественный активист',
    'about.coreValues': 'Наши основные ценности',
    'about.accessibilityTitle': 'Доступность прежде всего',
    'about.accessibilityDesc': 'Каждая функция разработана с учетом доступности, обеспечивая равный доступ для всех учащихся.',
    'about.communityTitle': 'Фокус на сообществе',
    'about.communityDesc': 'Строим мосты между слышащим и глухим сообществами через образование и понимание.',
    'about.qualityTitle': 'Качественное образование',
    'about.qualityDesc': 'Учебная программа высокого стандарта, разработанная сертифицированными инструкторами и экспертами сообщества.',
    'about.cultureTitle': 'Уважение к культуре',
    'about.cultureDesc': 'Почитая культуру глухих, адаптируем образование РЖЯ для казахстанского контекста.',
    'about.principlesNote': 'Эти основные принципы направляют все, что мы делаем в РЖЯ Казахстан.',
    'about.ourStory': 'Наша история',
    'about.storyText1': 'РЖЯ Казахстан родилась из простого, но мощного понимания: сообщество глухих и слабослышащих в Казахстане заслуживает доступа к высококачественному образованию жестового языка в своем регионе.',
    'about.storyText2': 'Наш основатель, Елена Волкова, заметила недостаток комплексных ресурсов РЖЯ, доступных на местном уровне. Большинство материалов были либо устаревшими, либо недоступными, либо не соответствующими культурному контексту Центральной Азии.',
    'about.storyText3': 'В 2021 году мы запустили РЖЯ Казахстан как онлайн-платформу, которая могла бы охватить студентов по всей стране, разрушая географические барьеры и предоставляя последовательное профессиональное обучение.',
    'about.storyText4': 'Сегодня мы с гордостью обслуживаем сотни студентов, от родителей, изучающих общение со своими глухими детьми, до профессионалов, стремящихся лучше служить сообществу глухих.',
    
    // Contact page
    'contact.title': 'Связаться с нами',
    'contact.subtitle': 'Свяжитесь с нашей командой. Мы здесь, чтобы помочь вам в вашем путешествии изучения РЖЯ.',
    'contact.getInTouch': 'Связаться с нами',
    'contact.name': 'Полное имя',
    'contact.namePlaceholder': 'Введите ваше полное имя',
    'contact.email': 'Адрес электронной почты',
    'contact.emailPlaceholder': 'Введите ваш адрес электронной почты',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'По какому вопросу?',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите, как мы можем вам помочь...',
    'contact.sendMessage': 'Отправить сообщение',
    'contact.contactInfo': 'Контактная информация',
    'contact.emailLabel': 'Эл. почта',
    'contact.emailValue': 'info@rslkazakhstan.kz',
    'contact.phoneLabel': 'Телефон',
    'contact.phoneValue': '+7 (727) 123-4567',
    'contact.addressLabel': 'Адрес',
    'contact.addressValue': 'Алматы, Казахстан',
    'contact.hoursLabel': 'Часы поддержки',
    'contact.hoursValue': 'Понедельник - Пятница, 9:00 - 18:00 (GMT+6)',
    'contact.socialMedia': 'Социальные сети',
    'contact.followText': 'Подписывайтесь на нас в социальных сетях для обновлений, советов и новостей сообщества.',
    'contact.faq': 'Часто задаваемые вопросы',
    'contact.faqSubtitle': 'Найдите быстрые ответы на распространенные вопросы о РЖЯ Казахстан и наших курсах.',
    'contact.faq1Q': 'Как начать изучать РЖЯ?',
    'contact.faq1A': 'Просто зарегистрируйте бесплатную учетную запись и просмотрите наши курсы для начинающих. Рекомендуем начать с курса "Алфавит и числа РЖЯ".',
    'contact.faq2Q': 'Подходят ли курсы для полных новичков?',
    'contact.faq2A': 'Абсолютно! Наши курсы разработаны с учетом потребностей начинающих, с четкими инструкциями и пошаговым прогрессом.',
    'contact.faq3Q': 'Могу ли я учиться в своем темпе?',
    'contact.faq3A': 'Да! Все наши курсы проходят в индивидуальном темпе. Вы можете учиться, когда вам удобно, 24/7.',
    'contact.faq4Q': 'Какому типу жестового языка вы обучаете?',
    'contact.faq4A': 'В настоящее время мы фокусируемся на русском жестовом языке (РЖЯ), но включаем культурный контекст, релевантный для Казахстана и Центральной Азии.',
    'contact.faq5Q': 'Выдаете ли вы сертификаты?',
    'contact.faq5A': 'Да, мы предоставляем сертификаты об окончании каждого курса, который вы успешно завершаете.',
    
    // Footer
    'footer.helpCenter': 'Центр помощи',
    'footer.accessibility': 'Доступность',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия обслуживания',
  },
  kz: {
    // Navigation
    'nav.home': 'Басты бет',
    'nav.courses': 'Курстар',
    'nav.about': 'Біз туралы',
    'nav.contact': 'Байланыс',
    'nav.signIn': 'Кіру',
    'nav.skipToMain': 'Негізгі мазмұнға өту',
    'nav.openMenu': 'Мәзірді ашу',
    'nav.closeMenu': 'Мәзірді жабу',
    'nav.homeLabel': 'ОИТ Қазақстан Басты бет',
    
    // Brand
    'brand.name': 'ОИТ Қазақстан',
    'brand.tagline': 'Жүрекпен үйрен',
    'brand.mission': 'Қазақстандағы саңырау және есту қабілеті нашар адамдарға қол жетімді, сапалы орыс ым тілін үйретудің арқасында мүмкіндіктерін кеңейту.',
    
    // Common
    'common.learnMore': 'Толығырақ',
    'common.getStarted': 'Бастау',
    'common.contact': 'Байланыс',
    'common.email': 'Эл. пошта',
    'common.phone': 'Телефон',
    'common.location': 'Орналасқан жері',
    'common.copyright': '© 2024 ОИТ Қазақстан. Барлық құқықтар сақталған. Саңырау қоғамы үшін ❤️ жасалған.',
    'common.followUs': 'Бізді қадағалаңыз:',
    'common.quickLinks': 'Жылдам сілтемелер',
    'common.support': 'Қолдау',
    
    // Home page
    'home.heroTitle': 'Қазақстанда орыс ым тілін үйреніңіз',
    'home.heroSubtitle': 'ОИТ Қазақстанға қосылып, саңырау және есту қабілеті нашар қоғаммен байланысыңыз. Орыс ым тіліндегі саяхатыңызды бүгін бастаңыз.',
    'home.startLearning': 'Бүгін үйренуді бастаңыз',
    'home.exploreCourses': 'Біздің курстарды зерттеу',
    'home.watchIntro': 'Кіріспені көру',
    'home.whyChoose': 'Неліктен ОИТ Қазақстанды таңдайды?',
    'home.qualityInstruction': 'Сапалы оқыту',
    'home.qualityDesc': 'Сертификатталған ОИТ нұсқаушыларынан жоғары сапалы бейнемазмұн және анық көрсетілімдермен үйреніңіз.',
    'home.flexibleLearning': 'Икемді оқыту',
    'home.flexibleDesc': 'Кез келген құрылғыда курстарға тәулік бойы қол жеткізумен өз қарқыныңызбен оқыңыз.',
    'home.supportiveCommunity': 'Қолдаушы қоғамдастық',
    'home.supportiveDesc': 'Оқушылар мен ым тілінің тасымалдаушыларының қостаған қоғамдастығына қосылыңыз.',
    'home.accessibleDesign': 'Қол жетімді дизайн',
    'home.accessibleDesc': 'Қол жетімділікті ескере отырып жасалған, барлығының тиімді үйренуін қамтамасыз етеді.',
    'home.testimonialTitle': 'Біздің студенттер не дейді',
    'home.testimonial1': 'ОИТ Қазақстан менің өмірімді өзгертті. Нұсқаушылар шыдамды, ал қоғамдастық өте қонақжай. Енді мен саңырау қызыммен сөйлесе аламын.',
    'home.testimonial1Author': 'Айда К.',
    'home.testimonial1Role': 'Ата-ана',
    'home.testimonial2': 'Бейненің сапасы керемет, құрылымдалған тәсіл маған тез ілгерілеуге көмектесті. Қатты ұсынамын!',
    'home.testimonial2Author': 'Марат С.',
    'home.testimonial2Role': 'Маман',
    'home.testimonial3': 'Саңырау студент ретінде мен бұл платформаның қаншалықты қол жетімді және инклюзивті екенін бағалаймын. Рахмет ОИТ Қазақстан!',
    'home.testimonial3Author': 'Жанна Б.',
    'home.testimonial3Role': 'Студент',
    'home.joinCommunity': 'ОИТ Қазақстанмен ым тілін үйреніп жатқан жүздеген студенттерге қосылыңыз.',
    'home.readyToStart': 'ОИТ саяхатыңызды бастауға дайынсыз ба?',
    
    // Courses page
    'courses.title': 'Біздің курстар',
    'courses.subtitle': 'Барлық дағды деңгейлері үшін кешенді орыс ым тілі курстары',
    'courses.beginner': 'Бастаушы',
    'courses.intermediate': 'Орташа',
    'courses.advanced': 'Жоғары',
    'courses.allLevels': 'Барлық деңгейлер',
    'courses.lessons': 'сабақ',
    'courses.minutes': 'минут',
    'courses.enrollNow': 'Қазір жазылу',
    'courses.viewDetails': 'Толығырақ көру',
    'courses.alphabetTitle': 'ОИТ әліпбиі және сандар',
    'courses.alphabetDesc': 'Әліпби және сан жүйесімен орыс ым тілінің негіздерін меңгеріңіз.',
    'courses.basicTitle': 'Негізгі сөйлесулер',
    'courses.basicDesc': 'Күнделікті сөйлесу үшін негізгі сөйлемдер мен сөздік қорын үйреніңіз.',
    'courses.familyTitle': 'Отбасы және қарым-қатынастар',
    'courses.familyDesc': 'Отбасылық қарым-қатынастарды, эмоцияларды және жеке байланыстарды білдіріңіз.',
    'courses.workTitle': 'Кәсіби және іскерлік ОИТ',
    'courses.workDesc': 'Кәсіби ым тілі дағдыларымен мансабыңызды дамытыңыз.',
    
    // About page
    'about.title': 'ОИТ Қазақстан туралы',
    'about.subtitle': '2021 жылы құрылған ОИТ Қазақстан - Қазақстан мен Орталық Азиядағы саңырау және есту қабілеті нашар қоғамдастыққа қызмет етуге арналған алғашқы кешенді ым тілін оқыту платформасы.',
    'about.ourMission': 'Біздің миссиямыз',
    'about.ourMissionDesc': 'Инновациялық онлайн білім беру арқылы Қазақстандағы барлығына орыс ым тілін қол жетімді ету, саңырау қоғамдастығында коммуникация мен қосылуды дамыту.',
    'about.ourTeam': 'Біздің командамызбен танысыңыз',
    'about.instructor1Name': 'Елена Волкова',
    'about.instructor1Role': 'Жетекші ОИТ нұсқаушысы және негізін қалаушы',
    'about.instructor1Bio': '15 жылдан астам тәжірибесі бар сертификатталған ОИТ аудармашысы. Ым тілін барлығына қол жетімді ету туралы ынтызар.',
    'about.instructor1Cred1': 'Сертификатталған ОИТ аудармашысы',
    'about.instructor1Cred2': 'Арнайы білім берудің магистрі',
    'about.instructor2Name': 'Дмитрий Назарбаев',
    'about.instructor2Role': 'Аға ОИТ нұсқаушысы',
    'about.instructor2Bio': 'Саңырау қоғамдастығының адвокаты және бастаушыларға арналған ОИТ оқытуды мамандандырған тәжірибелі педагог.',
    'about.instructor2Cred1': 'Туа біткен ОИТ сөйлеушісі',
    'about.instructor2Cred2': 'Қоғамдық белсенді',
    'about.coreValues': 'Біздің негізгі құндылықтарымыз',
    'about.accessibilityTitle': 'Қол жетімділік бірінші',
    'about.accessibilityDesc': 'Әрбір функция қол жетімділікті ескере отырып жасалған, барлық оқушылар үшін тең қол жеткізуді қамтамасыз етеді.',
    'about.communityTitle': 'Қоғамдастыққа фокус',
    'about.communityDesc': 'Білім беру және түсіністік арқылы есту және саңырау қоғамдастықтары арасында көпірлер салу.',
    'about.qualityTitle': 'Сапалы білім беру',
    'about.qualityDesc': 'Сертификатталған нұсқаушылар мен қоғамдастық сарапшылары әзірлеген жоғары стандартты оқу бағдарламасы.',
    'about.cultureTitle': 'Мәдениетке құрмет',
    'about.cultureDesc': 'Саңырау мәдениетін құрметтей отырып, ОИТ білім беруін қазақстандық контекстке бейімдеу.',
    'about.principlesNote': 'Бұл негізгі принциптер ОИТ Қазақстанда жасайтын барлық нәрсені басқарады.',
    'about.ourStory': 'Біздің тарихымыз',
    'about.storyText1': 'ОИТ Қазақстан қарапайым, бірақ қуатты түсіністіктен туындады: Қазақстандағы саңырау және есту қабілеті нашар қоғамдастық өз аймағында жоғары сапалы ым тілін оқытуға қол жеткізуге лайық.',
    'about.storyText2': 'Біздің негізін қалаушы Елена Волкова жергілікті деңгейде қол жетімді кешенді ОИТ ресурстарының жетіспеушілігін байқады. Материалдардың көбісі не ескірген, не қол жетімсіз, не Орталық Азия контекстіне сәйкес келмеді.',
    'about.storyText3': '2021 жылы біз ОИТ Қазақстанды елдің барлық жерінен студенттерге қол жеткізе алатын онлайн платформа ретінде іске қостық, географиялық кедергілерді бұзып, дәйекті кәсіби оқытуды қамтамасыз еттік.',
    'about.storyText4': 'Бүгін біз саңырау балаларымен сөйлесуді үйреніп жатқан ата-аналардан бастап саңырау қоғамдастыққа жақсырақ қызмет етуді көздеген мамандарға дейін жүздеген студенттерге қызмет көрсетуге мақтанамыз.',
    
    // Contact page
    'contact.title': 'Бізбен байланыс',
    'contact.subtitle': 'Біздің командамызбен байланысыңыз. Біз сіздің ОИТ үйрену саяхатыңызда көмектесу үшін мұндамыз.',
    'contact.getInTouch': 'Байланысу',
    'contact.name': 'Толық аты',
    'contact.namePlaceholder': 'Толық атыңызды енгізіңіз',
    'contact.email': 'Электрондық пошта мекенжайы',
    'contact.emailPlaceholder': 'Электрондық пошта мекенжайыңызды енгізіңіз',
    'contact.subject': 'Тақырып',
    'contact.subjectPlaceholder': 'Бұл не туралы?',
    'contact.message': 'Хабарлама',
    'contact.messagePlaceholder': 'Бізге қалай көмектесе алатынымызды айтыңыз...',
    'contact.sendMessage': 'Хабарлама жіберу',
    'contact.contactInfo': 'Байланыс ақпараты',
    'contact.emailLabel': 'Эл. пошта',
    'contact.emailValue': 'info@rslkazakhstan.kz',
    'contact.phoneLabel': 'Телефон',
    'contact.phoneValue': '+7 (727) 123-4567',
    'contact.addressLabel': 'Мекенжай',
    'contact.addressValue': 'Алматы, Қазақстан',
    'contact.hoursLabel': 'Қолдау сағаттары',
    'contact.hoursValue': 'Дүйсенбі - Жұма, 9:00 - 18:00 (GMT+6)',
    'contact.socialMedia': 'Әлеуметтік медиа',
    'contact.followText': 'Жаңартулар, кеңестер және қоғамдастық жаңалықтары үшін әлеуметтік медиада бізді қадағалаңыз.',
    'contact.faq': 'Жиі қойылатын сұрақтар',
    'contact.faqSubtitle': 'ОИТ Қазақстан және біздің курстар туралы жалпы сұрақтарға жылдам жауаптарды табыңыз.',
    'contact.faq1Q': 'ОИТ үйренуді қалай бастауға болады?',
    'contact.faq1A': 'Жай ғана тегін тіркелгі жасаңыз және бастаушыларға арналған курстарымызды қарап шығыңыз. "ОИТ әліпбиі және сандар" курсынан бастауды ұсынамыз.',
    'contact.faq2Q': 'Курстар толық бастаушыларға сәйкес келе ме?',
    'contact.faq2A': 'Әрине! Біздің курстарымыз бастаушыларды ескере отырып жасалған, анық нұсқаулықтар мен сатылай ілгерілеумен.',
    'contact.faq3Q': 'Өз қарқынымда үйрене аламын ба?',
    'contact.faq3A': 'Иә! Біздің барлық курстарымыз жеке қарқынмен өтеді. Сізге ыңғайлы уақытта, тәулік бойы үйрене аласыз.',
    'contact.faq4Q': 'Қандай ым тілін үйретесіздер?',
    'contact.faq4A': 'Қазір біз орыс ым тіліне (ОИТ) назар аударамыз, бірақ Қазақстан мен Орталық Азияға қатысты мәдени контекстті қамтимыз.',
    'contact.faq5Q': 'Сертификаттар беріп тұрасыздар ма?',
    'contact.faq5A': 'Иә, біз сәтті аяқтаған әрбір курс үшін аяқтау сертификаттарын береміз.',
    
    // Footer
    'footer.helpCenter': 'Көмек орталығы',
    'footer.accessibility': 'Қол жетімділік',
    'footer.privacy': 'Құпиялық саясаты',
    'footer.terms': 'Қызмет шарттары',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};